# Class exercises - configuration for multiple class
---
classes:
  - class_id: "yBoHxNLfmsCc7Cv6E"
    exercises:
      # `file` is relative to .strigo directory
      - file: "../setup/README.md"
        title: "Workshop Environment Validation"
      - file: "../spring-native/spring-native-app/README.md"
        title: "Building and running a JVM and Native image for a Spring app"
      - file: "../complete/clr-native/README.md"
        title: "Building and containerizing a Spring app in a lightweight container"
  - class_id: "nwPhxzqqK6XYdN7eD"
    exercises:
      # `file` is relative to .strigo directory
      - file: "../setup/README.md"
        title: "Workshop Environment Validation"
      - file: "../graalvm/class-initialization/README.md"
        title: "Understanding build-time vs run-time initialization"
      - file: "../spring-native/spring-native-app/README.md"
        title: "Building and running a JVM and Native image for a Spring app"
